import pygame, os , time
pygame.init()
running = True
WIDTH = 100
HEIGHT= 250
screen = pygame.display.set_mode((WIDTH,HEIGHT))
pygame.display.set_caption("Walking Animation")
p1 = os.path.join("images","walking1.png")
p2 = os.path.join("images","walking2.png")
p3 = os.path.join("images","walking3.png")
p4 = os.path.join("images","walking4.png")
p5 = os.path.join("images","walking5.png")
pic1 = pygame.image.load(p1)
pic2 = pygame.image.load(p2)
pic3 = pygame.image.load(p3)
pic4 = pygame.image.load(p4)
pic5 = pygame.image.load(p5)
i1 = pygame.transform.scale(pic1,(WIDTH,HEIGHT))
i2 = pygame.transform.scale(pic2,(WIDTH,HEIGHT))
i3 = pygame.transform.scale(pic3,(WIDTH,HEIGHT))
i4 = pygame.transform.scale(pic4,(WIDTH,HEIGHT))
i5 = pygame.transform.scale(pic5,(WIDTH,HEIGHT))
t = 0.2
while running:
    screen.blit(i1,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i2,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i3,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i4,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i5,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i1,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i2,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i3,(0,0))
    pygame.display.update()
    time.sleep(t)
    screen.blit(i4,(0,0))
    pygame.display.update()
    time.sleep(t)